### ISSUE TITLE
Deprecate and Remove URL.createObjectURL

### ISSUE THREAD

**Issue by ChristianHarms** [Affectiva/js-sdk-tests#5]
In the Chrome 71 the URL.createObjectURL call will be removed. The warning pops in the developer console and is located in https://download.affectiva.com/js/3.2/affdex.js (Line 300):

affdex.js:300 [Deprecation] URL.createObjectURL with media streams is deprecated and will be removed in M71, around December 2018. Please use HTMLMediaElement.srcObject instead. See https://www.chromestatus.com/features/5618491470118912 for more details.

**Comment by j4y** [comment]
There is an updated version of the Javascript SDK that addresses that issue.

Instead of
```
https://download.affectiva.com/js/3.2/affdex.js
```
just use
```
https://download.affectiva.com/js/3.2.1/affdex.js
```

**Comment by ChristianHarms** [comment]
Thank you - I found only the old urls in the documentation.
